
#Variables de Sistema

DB_DATABASE=master_tyres_db
DB_PASSWORD=?%4#JY9U6qdc
DB_USER=MasterTyres

SUPABASE_APIKEY=sb_secret_hOmPYGdlJZJX8bDMsu_irA_Ujo4NK9E
SUPABASE_BUCKET=Respaldos
SUPABASE_URL=https://gaxposmbmsjkagjmvlio.supabase.co