
#Variables de Sistema

DB_DATABASE=${DB_NAME:mastertyres}
DB_USER=${DB_USER:root}

supabase.api.key=${SUPABASE_APIKEY}
supabase.bucket=${SUPABASE_BUCKET}
supabase.url=${SUPABASE_URL}


# ?? Base de datos ?????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mastertyres}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

# ?? JPA / Hibernate ???????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# ?? JWT ???????????????????????????????????????????????????????
jwt.secret=${JWT_SECRET:clave_por_defecto_solo_dev}

# ?? Mail ??????????????????????????????????????????????????????
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? DevTools OFF en producción ????????????????????????????????
spring.devtools.restart.enabled=false

